const test=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const vm=require('node:vm');const source=fs.readFileSync('js/passport-apoio.js','utf8');
function fixture(options={}){const nodes=Object.fromEntries(['copy-pix','pix-status','share-passport','share-status'].map(id=>[id,{textContent:'',addEventListener(_,fn){this.click=fn}}]));let copied,shared,removed=false,focused=false;
 const navigator={clipboard:options.fallback?undefined:{writeText:async text=>{if(options.denied)throw Error('denied');copied=text}}};if(options.share)navigator.share=async data=>{if(options.share==='abort')throw{name:'AbortError'};if(options.share==='failed')throw Error('failed');shared=data};
 const document={body:{classList:{contains:()=>!options.otherPage},append(){}},activeElement:{focus(){focused=true}},getElementById:id=>nodes[id],createElement:()=>({style:{},setAttribute(){},select(){},remove(){removed=true}}),execCommand:cmd=>{assert.equal(cmd,'copy');return !options.noFallback}};
 vm.runInNewContext(source,{document,navigator});return{nodes,get copied(){return copied},get shared(){return shared},get removed(){return removed},get focused(){return focused}};}
test('Pix copies the exact official key',async()=>{const f=fixture();await f.nodes['copy-pix'].click();assert.equal(f.copied,'passportradio.online@gmail.com');assert.equal(f.nodes['pix-status'].textContent,'CHAVE COPIADA')});
test('clipboard denial cleans fallback and restores focus',async()=>{const f=fixture({denied:true});await f.nodes['copy-pix'].click();assert.equal(f.removed,true);assert.equal(f.focused,true);assert.equal(f.nodes['pix-status'].textContent,'CHAVE COPIADA')});
test('failed fallback offers manual copy without claiming success',async()=>{const f=fixture({fallback:true,noFallback:true});await f.nodes['copy-pix'].click();assert.equal(f.nodes['pix-status'].textContent,'Selecione a chave para copiar.')});
test('share uses native API when available',async()=>{const f=fixture({share:true});await f.nodes['share-passport'].click();assert.equal(f.shared.url,'https://www.passportradio.online/');assert.equal(f.copied,undefined)});
test('share cancellation leaves clipboard intact',async()=>{const f=fixture({share:'abort'});await f.nodes['share-passport'].click();assert.equal(f.copied,undefined);assert.equal(f.nodes['share-status'].textContent,'')});
for(const share of [undefined,'failed'])test('unsupported/failed share copies canonical Home URL: '+share,async()=>{const f=fixture({share});await f.nodes['share-passport'].click();assert.equal(f.copied,'https://www.passportradio.online/');assert.equal(f.nodes['share-status'].textContent,'LINK COPIADO')});
test('support handlers are not installed on other pages',()=>{const f=fixture({otherPage:true});assert.equal(f.nodes['copy-pix'].click,undefined)});
