const {test}=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');
const moduleReady=import('data:text/javascript;base64,'+Buffer.from(fs.readFileSync('supabase/functions/blog-aberto/logic.js')).toString('base64'));
const uid='10000000-0000-4000-8000-000000000001',owner='20000000-0000-4000-8000-000000000002';
const now=1791660000000;
const base={action:'submit',pseudonym:'Ouvinte',email:'forged@example.test',title:'Crítica musical fundamentada',category:'historias',body:'Não gostei deste disco: a produção abafou os instrumentos e prejudicou a interpretação.',rules:'sim',opened:now-5000};
function req(token){return new Request('https://example.test',{method:'POST',headers:token?{Authorization:'Bearer '+token}:{}})}
async function setup(user=uid,aal='aal1',verified=false){const m=await moduleReady;const store=m.createMemoryStore({controls:{submissions_open:true,attachments_open:true,interactions_closed:false}});const token='x.'+Buffer.from(JSON.stringify({aal})).toString('base64url')+'.x';let githubCalls=0;const ctx={store,clock:()=>now,env:{SUPABASE_URL:'https://project.test',SUPABASE_SERVICE_ROLE_KEY:'server-only-test-fixture',BLOG_ABERTO_ADMIN_USER_ID:owner},fetch:async(url)=>new Response(JSON.stringify(url.endsWith('/factors')?{all:verified?[{status:'verified'}]:[]}:{id:user,email:'account@example.test',email_confirmed_at:new Date(now).toISOString(),is_anonymous:false,factors:verified?[{status:'verified'}]:[]}),{status:200}),github:{mainSha:async()=>{githubCalls++;return 'sha'},ensureBranch:async()=>{},putFileOnBranch:async()=> 'sha',openPull:async()=>777,waitBuild:async()=>true,pullMerged:async()=>false,mergePull:async()=>{throw new Error('merge forbidden')}},live:async()=>false};return {m,ctx,store,token,githubCalls:()=>githubCalls};}
test('anonymous direct submission refused before writing or rate-limit',async()=>{const {m,ctx,store}=await setup();assert.equal((await m.dispatch(base,req(),ctx)).status,401);assert.equal(store.dump().blog_submissions.length,0);assert.equal(store.dump().blog_rate_limits.length,0)});
test('expired or forged token fails Auth validation',async()=>{const {m,ctx,store,token}=await setup();ctx.fetch=async()=>new Response('{}',{status:401});assert.equal((await m.dispatch(base,req(token),ctx)).status,401);assert.equal(store.dump().blog_submissions.length,0)});
for(const type of ['materia','banda','programa'])test('authenticated private submission: '+type,async()=>{const {m,ctx,store,token,githubCalls}=await setup();assert.equal((await m.dispatch({...base,participation_type:type,reference_links:'https://music.example.test/source',official_links:'https://artist.example.test'},req(token),ctx)).status,200);const row=store.dump().blog_submissions[0];assert.equal(row.user_id,uid);assert.equal(row.email,'account@example.test');assert.equal(row.participation_type,type);assert.equal(row.status,'recebida');assert.equal(row.approved_at,undefined);assert.equal(githubCalls(),0)});
for(const text of ['meu CPF: 12345678901','o endereço: Rua Particular 123','contato privado: pessoa@example.test','vamos exterminar todos os judeus','<script>alert(1)</script>','n\u200bigger'])test('server blocks unsafe text: '+text,async()=>{const {m,ctx,store,token}=await setup();assert.equal((await m.dispatch({...base,body:base.body+' '+text},req(token),ctx)).status,403);assert.equal(store.dump().blog_submissions.length,0)});
test('unconfirmed account rejected',async()=>{const {m,ctx,token}=await setup();ctx.fetch=async()=>new Response(JSON.stringify({id:uid,email:'x@example.test'}));assert.equal((await m.dispatch(base,req(token),ctx)).status,403)});
test('ordinary account cannot approve reject list or control',async()=>{const {m,ctx,token}=await setup();for(const action of ['admin-list','admin-approve','admin-reject','admin-control'])assert.equal((await m.dispatch({action,id:uid},req(token),ctx)).status,403)});
test('owner MFA remains required',async()=>{const {m,ctx,token}=await setup(owner,'aal1',true);assert.equal((await m.dispatch({action:'admin-session'},req(token),ctx)).status,403)});
test('owner approval prepares PR but never merges; rejection records reason',async()=>{const {m,ctx,store,token}=await setup(owner,'aal2',true);await m.dispatch(base,req(token),ctx);const row=store.dump().blog_submissions[0];const out=await m.dispatch({action:'admin-approve',id:row.id},req(token),ctx);assert.equal(out.status,200);assert.equal(out.body.status,'aprovada_aguardando');assert.equal(out.body.published,false);assert.equal(store.dump().blog_submissions[0].github_pr,777);assert.equal((await m.dispatch({action:'admin-reject',id:row.id,reason:'Falta contexto histórico verificável.'},req(token),ctx)).status,200);assert.equal(store.dump().blog_submissions[0].rejection_reason,'Falta contexto histórico verificável.')});
test('rights declaration and dangerous attachments enforced',async()=>{const {m,ctx,token}=await setup();assert.equal((await m.dispatch({...base,rules:''},req(token),ctx)).status,400);const file=new File(['%PDF-1.7 /JavaScript evil'],'file.pdf',{type:'application/pdf'});assert.equal((await m.dispatch({...base,attachment:file},req(token),ctx)).status,403)});
test('public comments and controls stay anonymous',async()=>{const {m,ctx}=await setup();const out=await m.dispatch({action:'public-controls'},req(),ctx);assert.equal(out.status,200);assert.equal(out.body.authentication_required,true);assert.equal((await m.dispatch({action:'public-comments',story_url:'/blog/test.html'},req(),ctx)).status,200)});
test('cross-origin www canonical is supported',async()=>{const {m,ctx}=await setup();const r=await m.handleRequest(new Request('https://project.test',{method:'OPTIONS',headers:{Origin:'https://www.passportradio.online'}}),ctx);assert.equal(r.headers.get('access-control-allow-origin'),'https://www.passportradio.online')});
