/* Consolidated footer QA; no acquisitions, audio playback or content rewrites. */
const fs=require('fs'),path=require('path'),http=require('http'),assert=require('assert');
const {chromium}=require('playwright');
const root=path.resolve(__dirname,'..'),out=path.join(root,'docs/universal-footer-20261010');
const excluded=new Set(['docs','tests','privado','assets','node_modules']);
const html=[];
function walk(dir){for(const e of fs.readdirSync(dir,{withFileTypes:true})){if(e.name.startsWith('.')||e.name.startsWith('_')||excluded.has(e.name))continue;const f=path.join(dir,e.name);if(e.isDirectory())walk(f);else if(e.name.endsWith('.html'))html.push(f);}}
walk(root);
let covered=0;
for(const f of html){const s=fs.readFileSync(f,'utf8');if(!s.toLowerCase().includes('</body>'))continue;assert(s.includes('data-passport-universal-footer defer'),f);covered++;}
const component=fs.readFileSync(path.join(root,'js/passport-universal-footer.js'),'utf8');
for(const p of ['pix.png','caixa.png','visa.png','mastercard.png','elo.png','amex.png','hipercard.png','diners.png','mercado-pago.svg'])assert(fs.statSync(path.join(root,'images/payments',p)).size>0,p);
const internal=[...component.matchAll(/'([^']+)','(\/[^']*)'/g)].map(m=>m[2]);
for(const u of internal){const f=path.join(root,u==='/'?'index.html':u.slice(1));assert(fs.existsSync(f),'missing footer destination '+u);}
const contentTypes={'.js':'application/javascript','.css':'text/css','.svg':'image/svg+xml','.png':'image/png','.json':'application/json','.html':'text/html','.ttf':'font/ttf','.woff2':'font/woff2'};
const server=http.createServer((req,res)=>{const url=new URL(req.url,'http://localhost'),name=decodeURIComponent(url.pathname),file=path.join(root,name==='/'?'index.html':name);if(!file.startsWith(root)||!fs.existsSync(file)||fs.statSync(file).isDirectory()){res.writeHead(404);res.end();return;}res.setHeader('Content-Type',contentTypes[path.extname(file)]||'application/octet-stream');fs.createReadStream(file).pipe(res);});
function sample(prefix){return html.find(f=>f.includes('/'+prefix))?.slice(root.length+1);}
const routes=['index.html','noticias.html','editorial.html','agenda.html','blog.html','bandas/index.html','jogos.html','videos.html','radio.html','loja.html','promocoes.html','anuncie.html','doe.html','divulgar-bandas.html','blog/arquivo/letras.html','blog/e/soundgarden.html','editorial/2026/10/09/a-forca-implacavel-de-badmotorfinger-na-historia-do-rock-7f648f963d.html',sample('loja/p/')].filter(Boolean);
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const origin=`http://127.0.0.1:${server.address().port}`;const browser=await chromium.launch({headless:true});const results=[];
try{for(const width of [1440,390]){const context=await browser.newContext({viewport:{width,height:1000}});const page=await context.newPage();
// Network streams are never opened; external images/fonts unrelated to footer are not collected.
await page.route('**/*',route=>{const u=new URL(route.request().url());if(u.origin!==origin)return route.abort();const p=u.pathname;if(/\.(mp3|m3u8|aac|mp4|webm)(?:$|\?)/i.test(p))return route.abort();return route.continue();});
for(const route of routes){await page.goto(origin+'/'+route,{waitUntil:'domcontentloaded'});await page.waitForSelector('[data-universal-footer-content]',{timeout:20000});await page.locator('[data-universal-footer-content]').scrollIntoViewIfNeeded();await page.evaluate(()=>document.fonts.ready);await page.waitForTimeout(500);
const result=await page.evaluate(()=>{const f=document.querySelector('[data-universal-footer-content]'),host=f.parentElement;const rect=f.getBoundingClientRect();return {path:location.pathname,active:document.querySelectorAll('[data-universal-footer-content]').length,visibleFooters:[...document.querySelectorAll('footer')].filter(n=>getComputedStyle(n).display!=='none').length,images:[...f.querySelectorAll('img')].map(i=>({alt:i.alt,src:i.getAttribute('src'),ok:i.complete&&i.naturalWidth>0,width:i.getBoundingClientRect().width,height:i.getBoundingClientRect().height})),order:[...f.children].map(e=>e.className),overflow:[...f.querySelectorAll('*')].some(n=>n.getBoundingClientRect().right>rect.right+1||n.getBoundingClientRect().left<rect.left-1),colors:{background:getComputedStyle(host).backgroundColor,ink:getComputedStyle(f).color,red:getComputedStyle(f.querySelector('.puf-wordmark')).color},brandHeights:[...f.querySelectorAll('.puf-brands img')].map(i=>i.getBoundingClientRect().height),outsideAudioAutoplay:[...document.querySelectorAll('audio,video')].some(e=>e.autoplay)};});
assert.equal(result.active,1);assert.equal(result.visibleFooters,1);assert.equal(result.images.length,9);assert(result.images.every(i=>i.ok));assert(!result.overflow);assert.deepEqual(result.order,['puf-identity','puf-navigation','puf-payments','puf-legal']);assert(result.brandHeights.every(h=>h===28));assert.equal(result.colors.background,'rgb(255, 255, 255)');assert.equal(result.colors.ink,'rgb(17, 17, 17)');assert.equal(result.colors.red,'rgb(196, 30, 58)');
results.push({viewport:width,...result});
if(['index.html','blog.html','loja.html'].includes(route))await page.locator('[data-universal-footer-content]').screenshot({path:path.join(out,route.replace('.html','')+'-'+width+'.png')});
}
// Framework-safe idempotence, dynamically inserted footers, and continuity-control node identity.
await page.evaluate(()=>{const host=document.querySelector('footer[data-passport-universal-footer]');const control=document.createElement('div');control.className='passport-continuity-controls';control.textContent='QA continuity node';host.append(control);window.__footerQAControl=control;const audio=document.createElement('audio');audio.volume=.35;window.__footerQAAudio=audio;window.PassportUniversalFooter.mount();window.PassportUniversalFooter.mount();});
const safe=await page.evaluate(()=>({same:document.querySelector('footer[data-passport-universal-footer]').contains(window.__footerQAControl),visible:getComputedStyle(window.__footerQAControl).display!=='none',volume:window.__footerQAAudio.volume,playing:!window.__footerQAAudio.paused,count:document.querySelectorAll('[data-universal-footer-content]').length}));assert(safe.same&&safe.visible);assert.equal(safe.volume,.35);assert.equal(safe.playing,false);assert.equal(safe.count,1);await context.close();}
fs.writeFileSync(path.join(out,'VALIDATION.json'),JSON.stringify({public_html_coverage:covered,routes_tested:routes.length,viewports:[1440,390],checks:results,idempotence_and_existing_control_nodes:'PASS',audio_playback_performed:false},null,2));console.log(`PASS: ${covered} HTML; ${routes.length} routes × 2 viewports; 9 original image assets + original boleto icon; existing controls retained.`);
}finally{await browser.close();server.close();}})().catch(e=>{console.error(e);server.close();process.exitCode=1;});
