const fs=require('fs'),path=require('path'),http=require('http'),assert=require('assert'),cp=require('child_process');
const {chromium}=require('playwright');const root=path.resolve(__dirname,'..'),out=path.join(root,'docs/participe-auth-20261010');fs.mkdirSync(out,{recursive:true});
const captureOnly=process.env.PARTICIPE_VISUAL_ONLY==='1';
const base='2ed6442f47c3621588c5a38e29325680c783c18d';
for(const f of ['js/passport-universal-footer.js','css/passport-universal-footer.css','js/passport-participe.js'])assert.equal(fs.readFileSync(path.join(root,f),'utf8'),cp.execFileSync('git',['show',base+':'+f],{cwd:root}).toString());
const before=cp.execFileSync('git',['show',base+':divulgar-bandas.html'],{cwd:root}).toString(),after=fs.readFileSync(path.join(root,'divulgar-bandas.html'),'utf8');
for(const pattern of [/<header.*?<\/nav>/s,/<figure class="participe-marrs">.*?<\/figure>/s,/<section class="participe-paper-support".*?<\/footer>/s])assert.equal(after.match(pattern)[0],before.match(pattern)[0]);
const mock=`(()=>{let session=null;const listeners=[];const listener=(event,session)=>listeners.forEach(f=>f(event,session));window.__authCalls=[];window.supabase={createClient:()=>({auth:{getSession:async()=>({data:{session}}),getUser:async()=>({data:{user:session?.user}}),onAuthStateChange:f=>{listeners.push(f);return {}},signInWithPassword:async()=>{session={access_token:'fixture-only',user:{id:'10000000-0000-4000-8000-000000000001',email:'private@example.test',user_metadata:{display_name:'Ouvinte'}}};listener('SIGNED_IN',session);return {data:{session}}},signUp:async p=>{window.__authCalls.push({method:'signUp',redirect:p.options.emailRedirectTo});return {data:{session:null}}},resetPasswordForEmail:async(e,p)=>{window.__authCalls.push({method:'recovery',redirect:p.redirectTo});return {}},updateUser:async()=>({}),signOut:async()=>{session=null;listener('SIGNED_OUT',null);return {}}},from:()=>({select:()=>({eq:()=>({maybeSingle:async()=>({data:null}),then:r=>r({data:[]})})})})})};})();`;
const types={'.html':'text/html','.js':'application/javascript','.css':'text/css','.json':'application/json','.png':'image/png','.jpg':'image/jpeg','.svg':'image/svg+xml','.woff2':'font/woff2','.ttf':'font/ttf'};
const server=http.createServer((req,res)=>{const u=new URL(req.url,'http://localhost'),f=path.join(root,decodeURIComponent(u.pathname));if(!f.startsWith(root)||!fs.existsSync(f)||!fs.statSync(f).isFile()){res.writeHead(404);return res.end()}res.setHeader('Content-Type',types[path.extname(f)]||'application/octet-stream');fs.createReadStream(f).pipe(res)});
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const origin='http://127.0.0.1:'+server.address().port;const browser=await chromium.launch({headless:true});const results=[];
try{for(const width of [1440,390]){
const context=await browser.newContext({viewport:{width,height:900}});await context.route('https://cdn.jsdelivr.net/npm/@supabase/**',route=>route.fulfill({contentType:'application/javascript',body:mock}));
await context.route('**/functions/v1/blog-aberto',async route=>{const req=route.request();if(req.postData()?.includes('public-controls'))return route.fulfill({json:{ok:true,submissions:true,attachments:true,comments:true}});assert.equal(req.headers().authorization,'Bearer fixture-only');return route.fulfill({json:{ok:true,message:'Recebido.'}})});
const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(origin+'/divulgar-bandas.html');await page.waitForSelector('#login-form');await page.waitForSelector('[data-universal-footer-content]');assert(await page.locator('#ba-send').isHidden());assert.equal(await page.locator('#participe-title').textContent(),'TEM UMA HISTÓRIA SOBRE MÚSICA? MANDA.');
assert(await page.locator('.participe-marrs img').evaluate(img=>img.complete&&img.naturalWidth>0));assert.equal(await page.locator('[data-universal-footer-content]').count(),1);
if(await page.locator('#passport-cookie-notice button').count()) await page.locator('#passport-cookie-notice button').click();
await page.locator('[data-auth-embedded]').screenshot({path:path.join(out,`account-${width}.png`)});await page.locator('[data-universal-footer-content]').screenshot({path:path.join(out,`footer-${width}.png`)});
if(captureOnly){await page.fill('#login-email','private@example.test');await page.fill('#login-password','test-fixture-password');await page.locator('#login-form button[type=submit]').click();await page.waitForSelector('#ba-send',{state:'visible'});await page.locator('.auth-card:has(#ba-send)').screenshot({path:path.join(out,`submission-${width}.png`)});results.push({width,cookie_notice:'accepted by its existing button',capture:'rendered branch UI, Auth fixture',footer:'unchanged'});await context.close();continue;}
await page.locator('[data-auth-view="signup"]').click();await page.fill('#signup-name','Ouvinte');await page.fill('#signup-email','private@example.test');await page.fill('#signup-password','test-fixture-password');await page.click('[data-password-toggle="signup-password"]');assert.equal(await page.locator('#signup-password').getAttribute('type'),'text');await page.locator('#signup-form button[type=submit]').click();await page.waitForFunction(()=>document.getElementById('auth-message').textContent.includes('Confira seu e-mail'));
await page.locator('[data-auth-view="login"]').click();await page.fill('#login-email','private@example.test');await page.fill('#login-password','test-fixture-password');await page.click('#forgot-password');await page.waitForFunction(()=>document.getElementById('auth-message').textContent.includes('recuperação'));const calls=await page.evaluate(()=>window.__authCalls);assert(calls.every(x=>x.redirect.includes('returnTo=%2Fdivulgar-bandas.html%23manda')));
await page.locator('#login-form button[type=submit]').click();await page.waitForSelector('#account-panel',{state:'visible'});await page.waitForSelector('#ba-send',{state:'visible'});assert.equal(new URL(page.url()).pathname,'/divulgar-bandas.html');
await page.locator('[data-participation="programa"]').click();assert.equal(await page.locator('[name=participation_type]').inputValue(),'programa');await page.fill('[name=title]','História do programa musical');await page.fill('[name=body]','Este é um ensaio privado para validar somente a interface do envio autenticado.');await page.check('[name=rules]');await page.locator('#ba-send button[type=submit]').click();await page.waitForFunction(()=>document.querySelector('.ba-result').textContent==='Recebido.');await page.locator('#ba-send').screenshot({path:path.join(out,`submission-${width}.png`)});
assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await page.click('#logout-button');await page.waitForSelector('#ba-send',{state:'hidden'});
await page.goto(origin+'/minha-passport.html?recovery=1&returnTo=%2Fdivulgar-bandas.html%23manda');await page.waitForSelector('#recovery-form',{state:'visible'});assert.equal(await page.locator('body').evaluate(el=>getComputedStyle(el).backgroundColor),'rgb(255, 255, 255)');await page.fill('#recovery-password','test-fixture-new');await page.fill('#recovery-password-confirm','test-fixture-new');await page.locator('#recovery-form button[type=submit]').click();await page.waitForFunction(()=>document.getElementById('auth-message').textContent.includes('Senha atualizada'));assert.equal(errors.length,0,JSON.stringify(errors));
results.push({width,rendered:true,signup_confirmation_message:'mocked Auth response',login_logout_reset:'mocked Auth responses',private_submission:'mocked endpoint',return_callback:'PASS',no_horizontal_overflow:true,mike_marrs_loaded:true,universal_footer_count:1,preserved_header_image_support_footer:'byte-identical'});await context.close();}
fs.writeFileSync(path.join(out,captureOnly?'VISUAL-CAPTURES.json':'BROWSER-VALIDATION.json'),JSON.stringify({base,production_auth_emails_tested:false,checks:results},null,2));console.log('PASS desktop/mobile account and authenticated submission UI; Auth responses mocked, no real emails or public test articles.');
}finally{await browser.close();server.close()}})().catch(e=>{console.error(e);server.close();process.exitCode=1});
