#!/usr/bin/env node
'use strict';

/*
 Passport Radio WhatsApp Channel local bridge.

 Runs only on a machine controlled by Passport Radio. Authentication material is
 stored under .passport-wa-auth/ and MUST NOT be committed. The bridge consumes
 data/whatsapp-channel-outbox.json generated by the Blog Tunnel and publishes
 each unseen item to the configured Channel/newsletter JID.

 Install locally:
   npm install @whiskeysockets/baileys pino
 Pair once with the Passport Radio WhatsApp Business account:
   node tools/whatsapp_channel_bridge.mjs --pair
 Then run:
   PASSPORT_WA_CHANNEL_JID='...@newsletter' node tools/whatsapp_channel_bridge.mjs
*/

import fs from 'node:fs';
import path from 'node:path';
import process from 'node:process';
import pino from 'pino';
import makeWASocket, {
  DisconnectReason,
  fetchLatestBaileysVersion,
  useMultiFileAuthState,
} from '@whiskeysockets/baileys';

const ROOT = process.cwd();
const AUTH_DIR = path.join(ROOT, '.passport-wa-auth');
const OUTBOX = path.join(ROOT, 'data', 'whatsapp-channel-outbox.json');
const STATE = path.join(ROOT, 'data', 'whatsapp-channel-local-state.json');
const pairMode = process.argv.includes('--pair');

function readJson(file, fallback) {
  try { return JSON.parse(fs.readFileSync(file, 'utf8')); }
  catch { return fallback; }
}
function atomicJson(file, value) {
  fs.mkdirSync(path.dirname(file), { recursive: true });
  const tmp = file + '.tmp';
  fs.writeFileSync(tmp, JSON.stringify(value, null, 2) + '\n', 'utf8');
  fs.renameSync(tmp, file);
}
function normalizeJid(value) {
  const jid = String(value || '').trim();
  if (!jid.endsWith('@newsletter')) {
    throw new Error('PASSPORT_WA_CHANNEL_JID must be the Passport Radio Channel newsletter JID');
  }
  return jid;
}
async function main() {
  const channelJid = normalizeJid(process.env.PASSPORT_WA_CHANNEL_JID);
  const { state, saveCreds } = await useMultiFileAuthState(AUTH_DIR);
  const { version } = await fetchLatestBaileysVersion();
  const sock = makeWASocket({
    auth: state,
    version,
    logger: pino({ level: 'warn' }),
    printQRInTerminal: pairMode,
    browser: ['Passport Radio', 'Chrome', '1.0.0'],
  });
  sock.ev.on('creds.update', saveCreds);

  await new Promise((resolve, reject) => {
    const timer = setTimeout(() => reject(new Error('WhatsApp connection timeout')), 120000);
    sock.ev.on('connection.update', ({ connection, lastDisconnect }) => {
      if (connection === 'open') {
        clearTimeout(timer); resolve();
      }
      if (connection === 'close') {
        const code = lastDisconnect?.error?.output?.statusCode;
        if (code === DisconnectReason.loggedOut) {
          clearTimeout(timer); reject(new Error('WhatsApp session logged out; pair again'));
        }
      }
    });
  });

  const outbox = readJson(OUTBOX, { items: [] });
  const local = readJson(STATE, { sent: [] });
  const sent = new Set(local.sent || []);
  let count = 0;

  for (const item of outbox.items || []) {
    if (!item?.id || sent.has(item.id)) continue;
    const text = String(item.text || '').trim();
    if (!text) continue;
    await sock.sendMessage(channelJid, { text });
    sent.add(item.id);
    atomicJson(STATE, { version: 1, sent: [...sent].sort() });
    count += 1;
    console.log('WhatsApp Channel published:', item.id);
  }

  console.log('WhatsApp Channel publication complete:', count);
  sock.end(undefined);
}

main().catch((err) => {
  console.error(err?.stack || err);
  process.exit(1);
});
